project:
  type: website


website:
  title: "GENIC"
  navbar:
    left:
      - text: "Home"
        href: home.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: false